//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doods.Xam.MonitorMyServer.Resx {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doods.Xam.MonitorMyServer.Resx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add commands.
        /// </summary>
        internal static string Add_Commands {
            get {
                return ResourceManager.GetString("Add_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apt.
        /// </summary>
        internal static string Apt {
            get {
                return ResourceManager.GetString("Apt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t connect.
        /// </summary>
        internal static string CanTConnect {
            get {
                return ResourceManager.GetString("CanTConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to add host.
        /// </summary>
        internal static string ClickAddHost {
            get {
                return ResourceManager.GetString("ClickAddHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click for searching.
        /// </summary>
        internal static string ClickForSearching {
            get {
                return ResourceManager.GetString("ClickForSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command name.
        /// </summary>
        internal static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command is required..
        /// </summary>
        internal static string CommandRequired {
            get {
                return ResourceManager.GetString("CommandRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commands.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection test.
        /// </summary>
        internal static string ConnectionTest {
            get {
                return ResourceManager.GetString("ConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dowloading.
        /// </summary>
        internal static string Dowloading {
            get {
                return ResourceManager.GetString("Dowloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enumerate all services..
        /// </summary>
        internal static string EnumerateAllServices {
            get {
                return ResourceManager.GetString("EnumerateAllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : no hosts detected.
        /// </summary>
        internal static string ErrorNoHostsDetected {
            get {
                return ResourceManager.GetString("ErrorNoHostsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HostName or IP.
        /// </summary>
        internal static string HostNameOrIp {
            get {
                return ResourceManager.GetString("HostNameOrIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A host name is required..
        /// </summary>
        internal static string HostNameRequired {
            get {
                return ResourceManager.GetString("HostNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hosts.
        /// </summary>
        internal static string Hosts {
            get {
                return ResourceManager.GetString("Hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installing packages.
        /// </summary>
        internal static string InstallingPackages {
            get {
                return ResourceManager.GetString("InstallingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install in progress.
        /// </summary>
        internal static string InstallInProgress {
            get {
                return ResourceManager.GetString("InstallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This field must be numeric integer..
        /// </summary>
        internal static string MustBeInt {
            get {
                return ResourceManager.GetString("MustBeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name to display.
        /// </summary>
        internal static string NameToDisplay {
            get {
                return ResourceManager.GetString("NameToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name to display is required..
        /// </summary>
        internal static string NameToDisplayRequired {
            get {
                return ResourceManager.GetString("NameToDisplayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New host.
        /// </summary>
        internal static string NewHost {
            get {
                return ResourceManager.GetString("NewHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No hosts detected :(.
        /// </summary>
        internal static string NoHostsDetected {
            get {
                return ResourceManager.GetString("NoHostsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à not finished.
        /// </summary>
        internal static string NotFinished {
            get {
                return ResourceManager.GetString("NotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oups.
        /// </summary>
        internal static string Oups {
            get {
                return ResourceManager.GetString("Oups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Packet reading.
        /// </summary>
        internal static string PacketReading {
            get {
                return ResourceManager.GetString("PacketReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A password is required..
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please set the URL without http(s)//.
        /// </summary>
        internal static string PleaseNoHttp {
            get {
                return ResourceManager.GetString("PleaseNoHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please set the URL with http(s)//.
        /// </summary>
        internal static string PleaseUseHttp {
            get {
                return ResourceManager.GetString("PleaseUseHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A port is required..
        /// </summary>
        internal static string PortRequired {
            get {
                return ResourceManager.GetString("PortRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Processes.
        /// </summary>
        internal static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching hosts.
        /// </summary>
        internal static string SearchingHosts {
            get {
                return ResourceManager.GetString("SearchingHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select host.
        /// </summary>
        internal static string SelectHost {
            get {
                return ResourceManager.GetString("SelectHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à there are {0} packages that can be updated.
        /// </summary>
        internal static string ThereAre_0_ItemsCanBeUpdated {
            get {
                return ResourceManager.GetString("ThereAre_0_ItemsCanBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are {0} of selected..
        /// </summary>
        internal static string ThereAre_0_OfSelected {
            get {
                return ResourceManager.GetString("ThereAre_0_OfSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à there are {0} processes..
        /// </summary>
        internal static string ThereAre_0_Processes {
            get {
                return ResourceManager.GetString("ThereAre_0_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à try to connect.
        /// </summary>
        internal static string TryToConnect {
            get {
                return ResourceManager.GetString("TryToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updates all.
        /// </summary>
        internal static string UpdatesAll {
            get {
                return ResourceManager.GetString("UpdatesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name or email.
        /// </summary>
        internal static string UserNameOrEmail {
            get {
                return ResourceManager.GetString("UserNameOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A username is required..
        /// </summary>
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
    }
}
