//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doods.Openmediavault.Mobile.Std.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class openmediavault_lvm2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal openmediavault_lvm2() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doods.Openmediavault.Mobile.Std.Resources.openmediavault-lvm2", typeof(openmediavault_lvm2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add physical volume.
        /// </summary>
        public static string AddPhysicalVolume {
            get {
                return ResourceManager.GetString("AddPhysicalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à After the logical volume has been extended you can resize the containing filesystem..
        /// </summary>
        public static string AfterTheLogicalVolumeHasBeenExtendedYouCanResizeTheContainingFilesystem_ {
            get {
                return ResourceManager.GetString("AfterTheLogicalVolumeHasBeenExtendedYouCanResizeTheContainingFilesystem.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create logical volume.
        /// </summary>
        public static string CreateLogicalVolume {
            get {
                return ResourceManager.GetString("CreateLogicalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create volume group.
        /// </summary>
        public static string CreateVolumeGroup {
            get {
                return ResourceManager.GetString("CreateVolumeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to create the logical volume?.
        /// </summary>
        public static string DoYouReallyWantToCreateTheLogicalVolume_ {
            get {
                return ResourceManager.GetString("DoYouReallyWantToCreateTheLogicalVolume?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to create the physical volume?.
        /// </summary>
        public static string DoYouReallyWantToCreateThePhysicalVolume_ {
            get {
                return ResourceManager.GetString("DoYouReallyWantToCreateThePhysicalVolume?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to create the volume group?.
        /// </summary>
        public static string DoYouReallyWantToCreateTheVolumeGroup_ {
            get {
                return ResourceManager.GetString("DoYouReallyWantToCreateTheVolumeGroup?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to resize the selected physical volume?.
        /// </summary>
        public static string DoYouReallyWantToResizeTheSelectedPhysicalVolume_ {
            get {
                return ResourceManager.GetString("DoYouReallyWantToResizeTheSelectedPhysicalVolume?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit logical volume.
        /// </summary>
        public static string EditLogicalVolume {
            get {
                return ResourceManager.GetString("EditLogicalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit volume group.
        /// </summary>
        public static string EditVolumeGroup {
            get {
                return ResourceManager.GetString("EditVolumeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extend.
        /// </summary>
        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extend logical volume.
        /// </summary>
        public static string ExtendLogicalVolume {
            get {
                return ResourceManager.GetString("ExtendLogicalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extend volume group.
        /// </summary>
        public static string ExtendVolumeGroup {
            get {
                return ResourceManager.GetString("ExtendVolumeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid name.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logical Volume Management.
        /// </summary>
        public static string LogicalVolumeManagement {
            get {
                return ResourceManager.GetString("LogicalVolumeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logical volumes.
        /// </summary>
        public static string LogicalVolumes {
            get {
                return ResourceManager.GetString("LogicalVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No free space available to create a logical volume..
        /// </summary>
        public static string NoFreeSpaceAvailableToCreateALogicalVolume_ {
            get {
                return ResourceManager.GetString("NoFreeSpaceAvailableToCreateALogicalVolume.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No free space available to extend the logical volume..
        /// </summary>
        public static string NoFreeSpaceAvailableToExtendTheLogicalVolume_ {
            get {
                return ResourceManager.GetString("NoFreeSpaceAvailableToExtendTheLogicalVolume.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Physical volumes.
        /// </summary>
        public static string PhysicalVolumes {
            get {
                return ResourceManager.GetString("PhysicalVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce.
        /// </summary>
        public static string Reduce {
            get {
                return ResourceManager.GetString("Reduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce volume group.
        /// </summary>
        public static string ReduceVolumeGroup {
            get {
                return ResourceManager.GetString("ReduceVolumeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select an device ....
        /// </summary>
        public static string SelectAnDevice___ {
            get {
                return ResourceManager.GetString("SelectAnDevice...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a volume group ....
        /// </summary>
        public static string SelectAVolumeGroup___ {
            get {
                return ResourceManager.GetString("SelectAVolumeGroup...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Used.
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume group.
        /// </summary>
        public static string VolumeGroup {
            get {
                return ResourceManager.GetString("VolumeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume groups.
        /// </summary>
        public static string VolumeGroups {
            get {
                return ResourceManager.GetString("VolumeGroups", resourceCulture);
            }
        }
    }
}
