//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doods.Openmediavault.Mobile.Std.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class openmediavault_clamav {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal openmediavault_clamav() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doods.Openmediavault.Mobile.Std.Resources.openmediavault_clamav", typeof(openmediavault_clamav).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add on-access scan.
        /// </summary>
        public static string AddOn_AccessScan {
            get {
                return ResourceManager.GetString("AddOn-AccessScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add scheduled job.
        /// </summary>
        public static string AddScheduledJob {
            get {
                return ResourceManager.GetString("AddScheduledJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Algorithmic detection.
        /// </summary>
        public static string AlgorithmicDetection {
            get {
                return ResourceManager.GetString("AlgorithmicDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An email message with the command output (if any produced) is send to the administrator..
        /// </summary>
        public static string AnEmailMessageWithTheCommandOutput_IfAnyProduced_IsSendToTheAdministrator_ {
            get {
                return ResourceManager.GetString("AnEmailMessageWithTheCommandOutput(IfAnyProduced)IsSendToTheAdministrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Antivirus.
        /// </summary>
        public static string Antivirus {
            get {
                return ResourceManager.GetString("Antivirus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be verbose..
        /// </summary>
        public static string BeVerbose_ {
            get {
                return ResourceManager.GetString("BeVerbose.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database checks.
        /// </summary>
        public static string DatabaseChecks {
            get {
                return ResourceManager.GetString("DatabaseChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date &amp; Time.
        /// </summary>
        public static string Date_Time {
            get {
                return ResourceManager.GetString("Date&Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day of month.
        /// </summary>
        public static string DayOfMonth {
            get {
                return ResourceManager.GetString("DayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day of week.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detect broken executables.
        /// </summary>
        public static string DetectBrokenExecutables {
            get {
                return ResourceManager.GetString("DetectBrokenExecutables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detect PUA.
        /// </summary>
        public static string DetectPUA {
            get {
                return ResourceManager.GetString("DetectPUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done ....
        /// </summary>
        public static string Done___ {
            get {
                return ResourceManager.GetString("Done...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit on-access scan.
        /// </summary>
        public static string EditOn_AccessScan {
            get {
                return ResourceManager.GetString("EditOn-AccessScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit scheduled job.
        /// </summary>
        public static string EditScheduledJob {
            get {
                return ResourceManager.GetString("EditScheduledJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable archive scanning..
        /// </summary>
        public static string EnableArchiveScanning_ {
            get {
                return ResourceManager.GetString("EnableArchiveScanning.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable HTML detection and normalisation..
        /// </summary>
        public static string EnableHTMLDetectionAndNormalisation_ {
            get {
                return ResourceManager.GetString("EnableHTMLDetectionAndNormalisation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable on-access virus scanning.
        /// </summary>
        public static string EnableOn_AccessVirusScanning {
            get {
                return ResourceManager.GetString("EnableOn-AccessVirusScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable scanning of ELF files..
        /// </summary>
        public static string EnableScanningOfELFFiles_ {
            get {
                return ResourceManager.GetString("EnableScanningOfELFFiles.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable scanning of OLE2 files, such as Microsoft Office documents and .msi files..
        /// </summary>
        public static string EnableScanningOfOLE2Files_SuchAsMicrosoftOfficeDocumentsAnd_MsiFiles_ {
            get {
                return ResourceManager.GetString("EnableScanningOfOLE2Files,SuchAsMicrosoftOfficeDocumentsAnd.MsiFiles.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable scanning within PDF files..
        /// </summary>
        public static string EnableScanningWithinPDFFiles_ {
            get {
                return ResourceManager.GetString("EnableScanningWithinPDFFiles.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable the algorithmic detection..
        /// </summary>
        public static string EnableTheAlgorithmicDetection_ {
            get {
                return ResourceManager.GetString("EnableTheAlgorithmicDetection.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable the detection of broken executables (both PE and ELF)..
        /// </summary>
        public static string EnableTheDetectionOfBrokenExecutables_BothPEAndELF__ {
            get {
                return ResourceManager.GetString("EnableTheDetectionOfBrokenExecutables(BothPEAndELF).", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable the detection of possibly unwanted applications..
        /// </summary>
        public static string EnableTheDetectionOfPossiblyUnwantedApplications_ {
            get {
                return ResourceManager.GetString("EnableTheDetectionOfPossiblyUnwantedApplications.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every N day of month.
        /// </summary>
        public static string EveryNDayOfMonth {
            get {
                return ResourceManager.GetString("EveryNDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every N hour.
        /// </summary>
        public static string EveryNHour {
            get {
                return ResourceManager.GetString("EveryNHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every N minute.
        /// </summary>
        public static string EveryNMinute {
            get {
                return ResourceManager.GetString("EveryNMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute scheduled job.
        /// </summary>
        public static string ExecuteScheduledJob {
            get {
                return ResourceManager.GetString("ExecuteScheduledJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extra options.
        /// </summary>
        public static string ExtraOptions {
            get {
                return ResourceManager.GetString("ExtraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow directory symlinks.
        /// </summary>
        public static string FollowDirectorySymlinks {
            get {
                return ResourceManager.GetString("FollowDirectorySymlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow directory symlinks..
        /// </summary>
        public static string FollowDirectorySymlinks_ {
            get {
                return ResourceManager.GetString("FollowDirectorySymlinks.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow file symlinks.
        /// </summary>
        public static string FollowFileSymlinks {
            get {
                return ResourceManager.GetString("FollowFileSymlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow regular file symlinks..
        /// </summary>
        public static string FollowRegularFileSymlinks_ {
            get {
                return ResourceManager.GetString("FollowRegularFileSymlinks.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infected files.
        /// </summary>
        public static string InfectedFiles {
            get {
                return ResourceManager.GetString("InfectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log clean files.
        /// </summary>
        public static string LogCleanFiles {
            get {
                return ResourceManager.GetString("LogCleanFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log clean files. This drastically increases the log size..
        /// </summary>
        public static string LogCleanFiles_ThisDrasticallyIncreasesTheLogSize_ {
            get {
                return ResourceManager.GetString("LogCleanFiles.ThisDrasticallyIncreasesTheLogSize.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monitor the shared folder and scan new or modified files..
        /// </summary>
        public static string MonitorTheSharedFolderAndScanNewOrModifiedFiles_ {
            get {
                return ResourceManager.GetString("MonitorTheSharedFolderAndScanNewOrModifiedFiles.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multiscan.
        /// </summary>
        public static string Multiscan {
            get {
                return ResourceManager.GetString("Multiscan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n/a.
        /// </summary>
        public static string N_A {
            get {
                return ResourceManager.GetString("N/A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of database update checks per day. Set to 0 to disable..
        /// </summary>
        public static string NumberOfDatabaseUpdateChecksPerDay_SetTo0ToDisable_ {
            get {
                return ResourceManager.GetString("NumberOfDatabaseUpdateChecksPerDay.SetTo0ToDisable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On-access.
        /// </summary>
        public static string On_Access {
            get {
                return ResourceManager.GetString("On-Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On Access Scans.
        /// </summary>
        public static string OnAccessScans {
            get {
                return ResourceManager.GetString("OnAccessScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perform a deeper analysis of executable files..
        /// </summary>
        public static string PerformADeeperAnalysisOfExecutableFiles_ {
            get {
                return ResourceManager.GetString("PerformADeeperAnalysisOfExecutableFiles.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quarantine.
        /// </summary>
        public static string Quarantine {
            get {
                return ResourceManager.GetString("Quarantine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan archives.
        /// </summary>
        public static string ScanArchives {
            get {
                return ResourceManager.GetString("ScanArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan ELF.
        /// </summary>
        public static string ScanELF {
            get {
                return ResourceManager.GetString("ScanELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan HTML.
        /// </summary>
        public static string ScanHTML {
            get {
                return ResourceManager.GetString("ScanHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan OLE2.
        /// </summary>
        public static string ScanOLE2 {
            get {
                return ResourceManager.GetString("ScanOLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan PDF.
        /// </summary>
        public static string ScanPDF {
            get {
                return ResourceManager.GetString("ScanPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan Portable Executable.
        /// </summary>
        public static string ScanPortableExecutable {
            get {
                return ResourceManager.GetString("ScanPortableExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan the directory contents in parallel using available threads..
        /// </summary>
        public static string ScanTheDirectoryContentsInParallelUsingAvailableThreads_ {
            get {
                return ResourceManager.GetString("ScanTheDirectoryContentsInParallelUsingAvailableThreads.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scheduled Jobs.
        /// </summary>
        public static string ScheduledJobs {
            get {
                return ResourceManager.GetString("ScheduledJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send command output via email.
        /// </summary>
        public static string SendCommandOutputViaEmail {
            get {
                return ResourceManager.GetString("SendCommandOutputViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shared folder.
        /// </summary>
        public static string SharedFolder {
            get {
                return ResourceManager.GetString("SharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The location of the files to scan..
        /// </summary>
        public static string TheLocationOfTheFilesToScan_ {
            get {
                return ResourceManager.GetString("TheLocationOfTheFilesToScan.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The location of the files to scan on-access..
        /// </summary>
        public static string TheLocationOfTheFilesToScanOn_Access_ {
            get {
                return ResourceManager.GetString("TheLocationOfTheFilesToScanOn-Access.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The location which is used as quarantine..
        /// </summary>
        public static string TheLocationWhichIsUsedAsQuarantine_ {
            get {
                return ResourceManager.GetString("TheLocationWhichIsUsedAsQuarantine.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The option, how to handle infected files..
        /// </summary>
        public static string TheOption_HowToHandleInfectedFiles_ {
            get {
                return ResourceManager.GetString("TheOption,HowToHandleInfectedFiles.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verbose.
        /// </summary>
        public static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
    }
}
