//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doods.Openmediavault.Mobile.Std.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class openmediavault_usbbackup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal openmediavault_usbbackup() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doods.Openmediavault.Mobile.Std.Resources.openmediavault-usbbackup", typeof(openmediavault_usbbackup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add backup job.
        /// </summary>
        public static string AddBackupJob {
            get {
                return ResourceManager.GetString("AddBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An email message with the command output (if any produced) is send to the administrator..
        /// </summary>
        public static string AnEmailMessageWithTheCommandOutput_IfAnyProduced_IsSendToTheAdministrator_ {
            get {
                return ResourceManager.GetString("AnEmailMessageWithTheCommandOutput(IfAnyProduced)IsSendToTheAdministrator.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backup jobs.
        /// </summary>
        public static string BackupJobs {
            get {
                return ResourceManager.GetString("BackupJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compress.
        /// </summary>
        public static string Compress {
            get {
                return ResourceManager.GetString("Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compress file data during the transfer..
        /// </summary>
        public static string CompressFileDataDuringTheTransfer_ {
            get {
                return ResourceManager.GetString("CompressFileDataDuringTheTransfer.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete files on the receiving side that don&apos;t exist on sender..
        /// </summary>
        public static string DeleteFilesOnTheReceivingSideThatDon_tExistOnSender_ {
            get {
                return ResourceManager.GetString("DeleteFilesOnTheReceivingSideThatDon\'tExistOnSender.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done ....
        /// </summary>
        public static string Done___ {
            get {
                return ResourceManager.GetString("Done...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit backup job.
        /// </summary>
        public static string EditBackupJob {
            get {
                return ResourceManager.GetString("EditBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable archive mode..
        /// </summary>
        public static string EnableArchiveMode_ {
            get {
                return ResourceManager.GetString("EnableArchiveMode.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable this option to keep partially transferred files, otherwise they will be deleted if the transfer is interrupted..
        /// </summary>
        public static string EnableThisOptionToKeepPartiallyTransferredFiles_OtherwiseTheyWillBeDeletedIfTheTransferIsInterrupted_ {
            get {
                return ResourceManager.GetString("EnableThisOptionToKeepPartiallyTransferredFiles,OtherwiseTheyWillBeDeletedIfTheTr" +
                        "ansferIsInterrupted.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute backup job.
        /// </summary>
        public static string ExecuteBackupJob {
            get {
                return ResourceManager.GetString("ExecuteBackupJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à External storage device.
        /// </summary>
        public static string ExternalStorageDevice {
            get {
                return ResourceManager.GetString("ExternalStorageDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extra options.
        /// </summary>
        public static string ExtraOptions {
            get {
                return ResourceManager.GetString("ExtraOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From external storage to shared folder.
        /// </summary>
        public static string FromExternalStorageToSharedFolder {
            get {
                return ResourceManager.GetString("FromExternalStorageToSharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à From shared folder to external storage.
        /// </summary>
        public static string FromSharedFolderToExternalStorage {
            get {
                return ResourceManager.GetString("FromSharedFolderToExternalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep partially transferred files.
        /// </summary>
        public static string KeepPartiallyTransferredFiles {
            get {
                return ResourceManager.GetString("KeepPartiallyTransferredFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n/a.
        /// </summary>
        public static string N_A {
            get {
                return ResourceManager.GetString("N/A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please note that the web interface is blocked until the manually started backup job has been finished. However the backup job is automatically executed in the background when the storage device is connected to the host..
        /// </summary>
        public static string PleaseNoteThatTheWebInterfaceIsBlockedUntilTheManuallyStartedBackupJobHasBeenFinished_HoweverTheBackupJobIsAutomaticallyExecutedInTheBackgroundWhenTheStorageDeviceIsConnectedToTheHost_ {
            get {
                return ResourceManager.GetString("PleaseNoteThatTheWebInterfaceIsBlockedUntilTheManuallyStartedBackupJobHasBeenFini" +
                        "shed.HoweverTheBackupJobIsAutomaticallyExecutedInTheBackgroundWhenTheStorageDevi" +
                        "ceIsConnectedToTheHost.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preserve ACLs.
        /// </summary>
        public static string PreserveAcls {
            get {
                return ResourceManager.GetString("PreserveAcls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preserve extended attributes.
        /// </summary>
        public static string PreserveExtendedAttributes {
            get {
                return ResourceManager.GetString("PreserveExtendedAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preserve group.
        /// </summary>
        public static string PreserveGroup {
            get {
                return ResourceManager.GetString("PreserveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preserve modification times.
        /// </summary>
        public static string PreserveModificationTimes {
            get {
                return ResourceManager.GetString("PreserveModificationTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preserve owner.
        /// </summary>
        public static string PreserveOwner {
            get {
                return ResourceManager.GetString("PreserveOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preserve permissions.
        /// </summary>
        public static string PreservePermissions {
            get {
                return ResourceManager.GetString("PreservePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quiet.
        /// </summary>
        public static string Quiet {
            get {
                return ResourceManager.GetString("Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recurse into directories..
        /// </summary>
        public static string RecurseIntoDirectories_ {
            get {
                return ResourceManager.GetString("RecurseIntoDirectories.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recursive.
        /// </summary>
        public static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a device ....
        /// </summary>
        public static string SelectADevice___ {
            get {
                return ResourceManager.GetString("SelectADevice...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send command output via email..
        /// </summary>
        public static string SendCommandOutputViaEmail_ {
            get {
                return ResourceManager.GetString("SendCommandOutputViaEmail.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the destination permissions to be the same as the source permissions..
        /// </summary>
        public static string SetTheDestinationPermissionsToBeTheSameAsTheSourcePermissions_ {
            get {
                return ResourceManager.GetString("SetTheDestinationPermissionsToBeTheSameAsTheSourcePermissions.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the group of the destination file to be the same as the source file..
        /// </summary>
        public static string SetTheGroupOfTheDestinationFileToBeTheSameAsTheSourceFile_ {
            get {
                return ResourceManager.GetString("SetTheGroupOfTheDestinationFileToBeTheSameAsTheSourceFile.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set the owner of the destination file to be the same as the source file, but only if the receiving rsync is being run as the super-user..
        /// </summary>
        public static string SetTheOwnerOfTheDestinationFileToBeTheSameAsTheSourceFile_ButOnlyIfTheReceivingRsyncIsBeingRunAsTheSuper_User_ {
            get {
                return ResourceManager.GetString("SetTheOwnerOfTheDestinationFileToBeTheSameAsTheSourceFile,ButOnlyIfTheReceivingRs" +
                        "yncIsBeingRunAsTheSuper-User.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shared folder.
        /// </summary>
        public static string SharedFolder {
            get {
                return ResourceManager.GetString("SharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppress non-error messages..
        /// </summary>
        public static string SuppressNon_ErrorMessages_ {
            get {
                return ResourceManager.GetString("SuppressNon-ErrorMessages.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronise from/to directory on external storage device..
        /// </summary>
        public static string SynchroniseFrom_ToDirectoryOnExternalStorageDevice_ {
            get {
                return ResourceManager.GetString("SynchroniseFrom/ToDirectoryOnExternalStorageDevice.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The external storage device..
        /// </summary>
        public static string TheExternalStorageDevice_ {
            get {
                return ResourceManager.GetString("TheExternalStorageDevice.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The shared folder content is synchronised from/to the root of the external storage device if this option is not set. The name of the directory is taken from the shared folder..
        /// </summary>
        public static string TheSharedFolderContentIsSynchronisedFrom_ToTheRootOfTheExternalStorageDeviceIfThisOptionIsNotSet_TheNameOfTheDirectoryIsTakenFromTheSharedFolder_ {
            get {
                return ResourceManager.GetString("TheSharedFolderContentIsSynchronisedFrom/ToTheRootOfTheExternalStorageDeviceIfThi" +
                        "sOptionIsNotSet.TheNameOfTheDirectoryIsTakenFromTheSharedFolder.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The shared folder to synchronise when the external storage device is connected..
        /// </summary>
        public static string TheSharedFolderToSynchroniseWhenTheExternalStorageDeviceIsConnected_ {
            get {
                return ResourceManager.GetString("TheSharedFolderToSynchroniseWhenTheExternalStorageDeviceIsConnected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transfer modification times along with the files and update them on the remote system..
        /// </summary>
        public static string TransferModificationTimesAlongWithTheFilesAndUpdateThemOnTheRemoteSystem_ {
            get {
                return ResourceManager.GetString("TransferModificationTimesAlongWithTheFilesAndUpdateThemOnTheRemoteSystem.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update the destination ACLs to be the same as the source ACLs..
        /// </summary>
        public static string UpdateTheDestinationAclsToBeTheSameAsTheSourceAcls_ {
            get {
                return ResourceManager.GetString("UpdateTheDestinationAclsToBeTheSameAsTheSourceAcls.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update the destination extended attributes to be the same as the local ones..
        /// </summary>
        public static string UpdateTheDestinationExtendedAttributesToBeTheSameAsTheLocalOnes_ {
            get {
                return ResourceManager.GetString("UpdateTheDestinationExtendedAttributesToBeTheSameAsTheLocalOnes.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à USB Backup.
        /// </summary>
        public static string USBBackup {
            get {
                return ResourceManager.GetString("USBBackup", resourceCulture);
            }
        }
    }
}
