//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doods.Webmin.Webapi.Std.Resx.package_updates {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Webmin_package_updates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Webmin_package_updates() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doods.Webmin.Webapi.Std.Resx.package_updates.Webmin_package-updates", typeof(Webmin_package_updates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.
        /// </summary>
        internal static string @__norefs {
            get {
                return ResourceManager.GetString("__norefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action when update needed.
        /// </summary>
        internal static string index_action {
            get {
                return ResourceManager.GetString("index_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Just notify.
        /// </summary>
        internal static string index_action0 {
            get {
                return ResourceManager.GetString("index_action0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install security updates.
        /// </summary>
        internal static string index_action1 {
            get {
                return ResourceManager.GetString("index_action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install any updates.
        /// </summary>
        internal static string index_action2 {
            get {
                return ResourceManager.GetString("index_action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only Virtualmin related.
        /// </summary>
        internal static string index_all_0 {
            get {
                return ResourceManager.GetString("index_all_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All packages.
        /// </summary>
        internal static string index_all_1 {
            get {
                return ResourceManager.GetString("index_all_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Packages to show:.
        /// </summary>
        internal static string index_allsel {
            get {
                return ResourceManager.GetString("index_allsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update to version $1 advised : $2.
        /// </summary>
        internal static string index_bad {
            get {
                return ResourceManager.GetString("index_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update to version $1 not yet available : $1.
        /// </summary>
        internal static string index_bad2 {
            get {
                return ResourceManager.GetString("index_bad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available for installation.
        /// </summary>
        internal static string index_caninstall {
            get {
                return ResourceManager.GetString("index_caninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show All.
        /// </summary>
        internal static string index_clear {
            get {
                return ResourceManager.GetString("index_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found $1 matching packages ...
        /// </summary>
        internal static string index_count {
            get {
                return ResourceManager.GetString("index_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string index_desc {
            get {
                return ResourceManager.GetString("index_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email updates report to.
        /// </summary>
        internal static string index_email {
            get {
                return ResourceManager.GetString("index_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to fetch package list.
        /// </summary>
        internal static string index_err {
            get {
                return ResourceManager.GetString("index_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scheduled checking options.
        /// </summary>
        internal static string index_header {
            get {
                return ResourceManager.GetString("index_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install Selected Packages.
        /// </summary>
        internal static string index_install {
            get {
                return ResourceManager.GetString("index_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are $1 packages available for installation. Use the search box to find the ones you want to install..
        /// </summary>
        internal static string index_manynew {
            get {
                return ResourceManager.GetString("index_manynew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à States to display:.
        /// </summary>
        internal static string index_mode {
            get {
                return ResourceManager.GetString("index_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installed.
        /// </summary>
        internal static string index_mode_current {
            get {
                return ResourceManager.GetString("index_mode_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only new.
        /// </summary>
        internal static string index_mode_new {
            get {
                return ResourceManager.GetString("index_mode_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only security updates.
        /// </summary>
        internal static string index_mode_security {
            get {
                return ResourceManager.GetString("index_mode_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only updates.
        /// </summary>
        internal static string index_mode_updates {
            get {
                return ResourceManager.GetString("index_mode_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package.
        /// </summary>
        internal static string index_name {
            get {
                return ResourceManager.GetString("index_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New version $1.
        /// </summary>
        internal static string index_new {
            get {
                return ResourceManager.GetString("index_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No packages managed by an update system were found on your system!.
        /// </summary>
        internal static string index_none_all {
            get {
                return ResourceManager.GetString("index_none_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No new packages or packages available to be updated were found..
        /// </summary>
        internal static string index_none_both {
            get {
                return ResourceManager.GetString("index_none_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No new packages for installation were found..
        /// </summary>
        internal static string index_none_new {
            get {
                return ResourceManager.GetString("index_none_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No packages available to be updated were found..
        /// </summary>
        internal static string index_none_updates {
            get {
                return ResourceManager.GetString("index_none_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No update exists from version $1.
        /// </summary>
        internal static string index_noupdate {
            get {
                return ResourceManager.GetString("index_noupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running latest $1.
        /// </summary>
        internal static string index_ok {
            get {
                return ResourceManager.GetString("index_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh Available Packages.
        /// </summary>
        internal static string index_refresh {
            get {
                return ResourceManager.GetString("index_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New package repository options.
        /// </summary>
        internal static string index_repoheader {
            get {
                return ResourceManager.GetString("index_repoheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Repositories.
        /// </summary>
        internal static string index_reposdelete {
            get {
                return ResourceManager.GetString("index_reposdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page allows you to configure which respositories will be used for new or updated packages..
        /// </summary>
        internal static string index_reposdesc {
            get {
                return ResourceManager.GetString("index_reposdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable Repositories.
        /// </summary>
        internal static string index_reposdisable {
            get {
                return ResourceManager.GetString("index_reposdisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable Repositories.
        /// </summary>
        internal static string index_reposenable {
            get {
                return ResourceManager.GetString("index_reposenable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled?.
        /// </summary>
        internal static string index_reposenabled {
            get {
                return ResourceManager.GetString("index_reposenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository name.
        /// </summary>
        internal static string index_reposname {
            get {
                return ResourceManager.GetString("index_reposname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package URL.
        /// </summary>
        internal static string index_reposurl {
            get {
                return ResourceManager.GetString("index_reposurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à package list.
        /// </summary>
        internal static string index_return {
            get {
                return ResourceManager.GetString("index_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check for updates on schedule?.
        /// </summary>
        internal static string index_sched {
            get {
                return ResourceManager.GetString("index_sched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes, every.
        /// </summary>
        internal static string index_sched0 {
            get {
                return ResourceManager.GetString("index_sched0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string index_sched1 {
            get {
                return ResourceManager.GetString("index_sched1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à day.
        /// </summary>
        internal static string index_schedd {
            get {
                return ResourceManager.GetString("index_schedd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This form can be used to automatically install package updates on a regular schedule..
        /// </summary>
        internal static string index_scheddesc {
            get {
                return ResourceManager.GetString("index_scheddesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hour.
        /// </summary>
        internal static string index_schedh {
            get {
                return ResourceManager.GetString("index_schedh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à week.
        /// </summary>
        internal static string index_schedw {
            get {
                return ResourceManager.GetString("index_schedw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find packages matching:.
        /// </summary>
        internal static string index_search {
            get {
                return ResourceManager.GetString("index_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        internal static string index_searchok {
            get {
                return ResourceManager.GetString("index_searchok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string index_source {
            get {
                return ResourceManager.GetString("index_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        internal static string index_status {
            get {
                return ResourceManager.GetString("index_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package Updates.
        /// </summary>
        internal static string index_tabpkgs {
            get {
                return ResourceManager.GetString("index_tabpkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scheduled Upgrades.
        /// </summary>
        internal static string index_tabscheds {
            get {
                return ResourceManager.GetString("index_tabscheds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package Repositories.
        /// </summary>
        internal static string index_tabsrepos {
            get {
                return ResourceManager.GetString("index_tabsrepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Software Package Updates.
        /// </summary>
        internal static string index_title {
            get {
                return ResourceManager.GetString("index_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Selected Packages.
        /// </summary>
        internal static string index_update {
            get {
                return ResourceManager.GetString("index_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Webmin module $1.
        /// </summary>
        internal static string index_webmin {
            get {
                return ResourceManager.GetString("index_webmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Webmin theme $1.
        /// </summary>
        internal static string index_webmintheme {
            get {
                return ResourceManager.GetString("index_webmintheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created package repository $1.
        /// </summary>
        internal static string log_create_repo {
            get {
                return ResourceManager.GetString("log_create_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted package repository $1.
        /// </summary>
        internal static string log_delete_repo {
            get {
                return ResourceManager.GetString("log_delete_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted $1 package repositories.
        /// </summary>
        internal static string log_delete_repos {
            get {
                return ResourceManager.GetString("log_delete_repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled package repository $1.
        /// </summary>
        internal static string log_disable_repo {
            get {
                return ResourceManager.GetString("log_disable_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled $1 package repositories.
        /// </summary>
        internal static string log_disable_repos {
            get {
                return ResourceManager.GetString("log_disable_repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled package repository $1.
        /// </summary>
        internal static string log_enable_repo {
            get {
                return ResourceManager.GetString("log_enable_repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled $1 package repositories.
        /// </summary>
        internal static string log_enable_repos {
            get {
                return ResourceManager.GetString("log_enable_repos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refreshed available packages.
        /// </summary>
        internal static string log_refresh {
            get {
                return ResourceManager.GetString("log_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabled scheduled updates.
        /// </summary>
        internal static string log_sched {
            get {
                return ResourceManager.GetString("log_sched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disabled scheduled updates.
        /// </summary>
        internal static string log_unsched {
            get {
                return ResourceManager.GetString("log_unsched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installed $1 updated packages.
        /// </summary>
        internal static string log_update {
            get {
                return ResourceManager.GetString("log_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Re-fetching available packages ...
        /// </summary>
        internal static string refresh_available {
            get {
                return ResourceManager.GetString("refresh_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clearing package caches ...
        /// </summary>
        internal static string refresh_clearing {
            get {
                return ResourceManager.GetString("refresh_clearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. done.
        /// </summary>
        internal static string refresh_done {
            get {
                return ResourceManager.GetString("refresh_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. found $1 possible updates.
        /// </summary>
        internal static string refresh_done3 {
            get {
                return ResourceManager.GetString("refresh_done3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refreshing Packages.
        /// </summary>
        internal static string refresh_title {
            get {
                return ResourceManager.GetString("refresh_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No button clicked!.
        /// </summary>
        internal static string repos_ebutton {
            get {
                return ResourceManager.GetString("repos_ebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None selected.
        /// </summary>
        internal static string repos_enone {
            get {
                return ResourceManager.GetString("repos_enone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to create repository.
        /// </summary>
        internal static string repos_err_create {
            get {
                return ResourceManager.GetString("repos_err_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to delete repositories.
        /// </summary>
        internal static string repos_err_delete {
            get {
                return ResourceManager.GetString("repos_err_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to disable repositories.
        /// </summary>
        internal static string repos_err_disable {
            get {
                return ResourceManager.GetString("repos_err_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to enable repositories.
        /// </summary>
        internal static string repos_err_enable {
            get {
                return ResourceManager.GetString("repos_err_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Now.
        /// </summary>
        internal static string repos_ok {
            get {
                return ResourceManager.GetString("repos_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the $1 selected package repositories? Packages installed from them will still be available, but may not be updatable. .
        /// </summary>
        internal static string repos_rusure {
            get {
                return ResourceManager.GetString("repos_rusure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Repositories.
        /// </summary>
        internal static string repos_title {
            get {
                return ResourceManager.GetString("repos_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scheduled checking for updates has been disabled..
        /// </summary>
        internal static string sched_no {
            get {
                return ResourceManager.GetString("sched_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scheduled Update.
        /// </summary>
        internal static string sched_title {
            get {
                return ResourceManager.GetString("sched_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scheduled checking for updates is now active..
        /// </summary>
        internal static string sched_yes {
            get {
                return ResourceManager.GetString("sched_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à APT.
        /// </summary>
        internal static string system_apt {
            get {
                return ResourceManager.GetString("system_apt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CSW (Blastwave).
        /// </summary>
        internal static string system_csw {
            get {
                return ResourceManager.GetString("system_csw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Webmin or Usermin tar.gz.
        /// </summary>
        internal static string system_tgz {
            get {
                return ResourceManager.GetString("system_tgz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usermin module.
        /// </summary>
        internal static string system_usermin {
            get {
                return ResourceManager.GetString("system_usermin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Webmin module.
        /// </summary>
        internal static string system_webmin {
            get {
                return ResourceManager.GetString("system_webmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à YUM.
        /// </summary>
        internal static string system_yum {
            get {
                return ResourceManager.GetString("system_yum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install Now.
        /// </summary>
        internal static string update_confirm {
            get {
                return ResourceManager.GetString("update_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installing dependency $1 $2 ...
        /// </summary>
        internal static string update_depend {
            get {
                return ResourceManager.GetString("update_depend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installed package $1 $2..
        /// </summary>
        internal static string update_done {
            get {
                return ResourceManager.GetString("update_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. could not find current configuration directory!.
        /// </summary>
        internal static string update_econfigdir {
            get {
                return ResourceManager.GetString("update_econfigdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. could not get current install directory!.
        /// </summary>
        internal static string update_ecurdir {
            get {
                return ResourceManager.GetString("update_ecurdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. could not download $1 : $2.
        /// </summary>
        internal static string update_edownload {
            get {
                return ResourceManager.GetString("update_edownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not find package to update named $1.
        /// </summary>
        internal static string update_efindpkg {
            get {
                return ResourceManager.GetString("update_efindpkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not find $1 in available packages list..
        /// </summary>
        internal static string update_efound {
            get {
                return ResourceManager.GetString("update_efound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install failed : $1.
        /// </summary>
        internal static string update_einstall {
            get {
                return ResourceManager.GetString("update_einstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No packages selected.
        /// </summary>
        internal static string update_enone {
            get {
                return ResourceManager.GetString("update_enone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. upgrade failed! See the error message above for the reason why.
        /// </summary>
        internal static string update_etgzsetup {
            get {
                return ResourceManager.GetString("update_etgzsetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. extraction failed! See the error message above for the reason why.
        /// </summary>
        internal static string update_etgzuntar {
            get {
                return ResourceManager.GetString("update_etgzuntar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. failed : $1.
        /// </summary>
        internal static string update_ewdownload {
            get {
                return ResourceManager.GetString("update_ewdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. install failed : $1.
        /// </summary>
        internal static string update_ewinstall {
            get {
                return ResourceManager.GetString("update_ewinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No packages were installed. Check the messages above for the cause of the error..
        /// </summary>
        internal static string update_failed {
            get {
                return ResourceManager.GetString("update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New version.
        /// </summary>
        internal static string update_newver {
            get {
                return ResourceManager.GetString("update_newver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string update_none {
            get {
                return ResourceManager.GetString("update_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully installed $1 packages..
        /// </summary>
        internal static string update_ok {
            get {
                return ResourceManager.GetString("update_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current version.
        /// </summary>
        internal static string update_oldver {
            get {
                return ResourceManager.GetString("update_oldver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Building complete list of packages ...
        /// </summary>
        internal static string update_ops {
            get {
                return ResourceManager.GetString("update_ops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now updating $1 ...
        /// </summary>
        internal static string update_pkg {
            get {
                return ResourceManager.GetString("update_pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now installing $1 ...
        /// </summary>
        internal static string update_pkg2 {
            get {
                return ResourceManager.GetString("update_pkg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reboot Now.
        /// </summary>
        internal static string update_reboot {
            get {
                return ResourceManager.GetString("update_reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One of the installed packages requires a reboot to be fully applied..
        /// </summary>
        internal static string update_rebootdesc {
            get {
                return ResourceManager.GetString("update_rebootdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you wish to install the $1 packages listed below? This may include dependencies of packages that you selected..
        /// </summary>
        internal static string update_rusure {
            get {
                return ResourceManager.GetString("update_rusure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading latest version of $1 ...
        /// </summary>
        internal static string update_tgzdownload {
            get {
                return ResourceManager.GetString("update_tgzdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. downloaded $1.
        /// </summary>
        internal static string update_tgzdownloaded {
            get {
                return ResourceManager.GetString("update_tgzdownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Running setup script ...
        /// </summary>
        internal static string update_tgzsetup {
            get {
                return ResourceManager.GetString("update_tgzsetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. upgrade complete.
        /// </summary>
        internal static string update_tgzsetupdone {
            get {
                return ResourceManager.GetString("update_tgzsetupdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting archive file ...
        /// </summary>
        internal static string update_tgzuntar {
            get {
                return ResourceManager.GetString("update_tgzuntar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. done.
        /// </summary>
        internal static string update_tgzuntardone {
            get {
                return ResourceManager.GetString("update_tgzuntardone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Packages.
        /// </summary>
        internal static string update_title {
            get {
                return ResourceManager.GetString("update_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install Packages.
        /// </summary>
        internal static string update_title2 {
            get {
                return ResourceManager.GetString("update_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading Webmin module $1 ...
        /// </summary>
        internal static string update_wdownload {
            get {
                return ResourceManager.GetString("update_wdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. download complete.
        /// </summary>
        internal static string update_wdownloaded {
            get {
                return ResourceManager.GetString("update_wdownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installing Webmin module $1 ...
        /// </summary>
        internal static string update_winstall {
            get {
                return ResourceManager.GetString("update_winstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .. installation complete.
        /// </summary>
        internal static string update_winstalled {
            get {
                return ResourceManager.GetString("update_winstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available version.
        /// </summary>
        internal static string view_aversion {
            get {
                return ResourceManager.GetString("view_aversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changelog for available version.
        /// </summary>
        internal static string view_changelog {
            get {
                return ResourceManager.GetString("view_changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installed version.
        /// </summary>
        internal static string view_cversion {
            get {
                return ResourceManager.GetString("view_cversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package description.
        /// </summary>
        internal static string view_desc {
            get {
                return ResourceManager.GetString("view_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updatable package information.
        /// </summary>
        internal static string view_header {
            get {
                return ResourceManager.GetString("view_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Install Package.
        /// </summary>
        internal static string view_install {
            get {
                return ResourceManager.GetString("view_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package name.
        /// </summary>
        internal static string view_name {
            get {
                return ResourceManager.GetString("view_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage Package.
        /// </summary>
        internal static string view_software {
            get {
                return ResourceManager.GetString("view_software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installation source.
        /// </summary>
        internal static string view_source {
            get {
                return ResourceManager.GetString("view_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current state.
        /// </summary>
        internal static string view_state {
            get {
                return ResourceManager.GetString("view_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update system.
        /// </summary>
        internal static string view_system {
            get {
                return ResourceManager.GetString("view_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Package Details.
        /// </summary>
        internal static string view_title {
            get {
                return ResourceManager.GetString("view_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Package.
        /// </summary>
        internal static string view_update {
            get {
                return ResourceManager.GetString("view_update", resourceCulture);
            }
        }
    }
}
